name: Automated Approvals

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  automated-approvals:
    name: Automated Approvals
    permissions:
      pull-requests: read
      contents: read
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@1dd2a82736c07845531e3c10d18d75b7d71f3525
    secrets: inherit # pragma: allowlist secret
