name: Validate PR Title

on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review, synchronize ]

jobs:
  validate-title:
    name: Validate PR Title
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-conventional-commit-title.yml@1dd2a82736c07845531e3c10d18d75b7d71f3525
