name: Automated Approvals

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  automated-approvals:
    name: Automated Approvals
    permissions:
      pull-requests: read
      contents: read
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@c57235a204b77b6622a0e99fe29dca5eecf80b2f
    secrets: inherit # pragma: allowlist secret
